// Pumo Feed Log: the only module that talks to Supabase. All operations over REST/fetch.
// Never sends `created_at`. Never uses the HTTP hard-delete verb. Every `feeds` query is scoped
// to a `pet_id` except `getAllFeedsForExport`'s own paging (already pet-scoped) and `getPets`
// (which queries `pets`, not `feeds`). (contract.md §6, §8; architecture.md §4)

import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
import { REQUEST_TIMEOUT_MS, RECENT_LIST_SIZE, HISTORY_PAGE_SIZE } from './constants.js';
import { startOfFeedDay } from './logic.js';

const FEEDS_URL = `${SUPABASE_URL}/rest/v1/feeds`;
const PETS_URL = `${SUPABASE_URL}/rest/v1/pets`;

const BASE_HEADERS = {
  apikey: SUPABASE_PUBLISHABLE_KEY,
  Accept: 'application/json',
};

/**
 * Normalized failure shape for every api.js call. See contract.md §8.
 */
export class ApiError extends Error {
  constructor({ kind, status, code, message }) {
    super(message || kind);
    this.name = 'ApiError';
    this.kind = kind;
    this.status = status;
    this.code = code;
  }
}

/**
 * fetch with cache:'no-store' and a REQUEST_TIMEOUT_MS AbortController, translating every
 * rejection into an ApiError with kind 'timeout' | 'offline' | 'network'.
 */
async function rawFetch(url, options) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    return await fetch(url, { ...options, cache: 'no-store', signal: controller.signal });
  } catch (err) {
    if (controller.signal.aborted) {
      throw new ApiError({ kind: 'timeout', message: 'Request timed out' });
    }
    if (typeof navigator !== 'undefined' && navigator.onLine === false) {
      throw new ApiError({ kind: 'offline', message: 'Offline' });
    }
    throw new ApiError({ kind: 'network', message: (err && err.message) || 'Network error' });
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Throws a normalized 'http' ApiError for a non-OK, non-specially-handled response.
 * Parses and console.errors the PostgREST error body when present.
 * @param {Response} response
 * @returns {Promise<never>}
 */
async function throwHttpError(response) {
  let body = null;
  try {
    body = await response.json();
  } catch {
    // Body wasn't JSON (or was empty) — fall through with body = null.
  }
  if (body) console.error('[Pumo] API error', response.status, body);
  throw new ApiError({
    kind: 'http',
    status: response.status,
    code: body && body.code,
    message: (body && body.message) || response.statusText || `HTTP ${response.status}`,
  });
}

async function doGet(url) {
  const response = await rawFetch(url, { method: 'GET', headers: BASE_HEADERS });
  if (!response.ok) await throwHttpError(response);
  return response.json();
}

/**
 * The fixed pet list, ascending `sort_order`. Always 3+ rows once migrated, never empty.
 * (contract.md §6.G)
 * @returns {Promise<Array<{id: string, slug: string, name: string, species: string, sort_order: number, photo_url: string|null}>>}
 */
export async function getPets() {
  const url = `${PETS_URL}?select=id,slug,name,species,sort_order,photo_url&order=sort_order.asc`;
  return doGet(url);
}

/**
 * Last RECENT_LIST_SIZE live feeds for `petId`, newest first, plus that pet's today count.
 * Both requests run in parallel and both must succeed. (contract.md §6.A/B)
 * @param {Date} now
 * @param {string} petId
 * @returns {Promise<{recent: Array, todayCount: number, loadedAt: number}>}
 */
export async function getHomeData(now, petId) {
  const recentUrl =
    `${FEEDS_URL}?select=id,pet_id,created_at,logged_by&pet_id=eq.${encodeURIComponent(petId)}&deleted_at=is.null` +
    `&order=created_at.desc&limit=${RECENT_LIST_SIZE}`;

  const since = encodeURIComponent(startOfFeedDay(now).toISOString());
  const countUrl =
    `${FEEDS_URL}?select=id&pet_id=eq.${encodeURIComponent(petId)}&deleted_at=is.null&created_at=gte.${since}`;

  const [recent, countRows] = await Promise.all([doGet(recentUrl), doGet(countUrl)]);
  return { recent, todayCount: countRows.length, loadedAt: Date.now() };
}

/**
 * Logs one feed for `petId`. `id` is generated by the caller (logic.newFeedId) so a retry after
 * a lost response can safely reuse it. Never sends `created_at`. (contract.md §6.C)
 * @param {{id: string, petId: string, logged_by: string|null}} attempt
 * @returns {Promise<{id: string, pet_id: string, created_at: string, logged_by: string|null, deleted_at: string|null}>}
 */
export async function logFeed({ id, petId, logged_by }) {
  const response = await rawFetch(FEEDS_URL, {
    method: 'POST',
    headers: {
      ...BASE_HEADERS,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify({ id, pet_id: petId, logged_by }),
  });

  if (response.status === 201) {
    const rows = await response.json();
    return rows[0];
  }

  if (response.status === 409) {
    let body = null;
    try {
      body = await response.json();
    } catch {
      // fall through
    }
    if (body && body.code === '23505') {
      // An earlier attempt with this id already reached the database; its response was lost.
      // That's a success, not a failure — fetch the row and resolve with it.
      const rows = await doGet(
        `${FEEDS_URL}?select=id,pet_id,created_at,logged_by,deleted_at&id=eq.${encodeURIComponent(id)}`
      );
      if (rows.length > 0) return rows[0];
    }
    if (body) console.error('[Pumo] API error', response.status, body);
    throw new ApiError({
      kind: 'http',
      status: response.status,
      code: body && body.code,
      message: (body && body.message) || 'Conflict',
    });
  }

  return throwHttpError(response);
}

/**
 * Soft-deletes a feed (used for both Undo and Delete). Only ever PATCHes `deleted_at`. Takes
 * only `id`, never `pet_id` — a feed's id is already globally unique. (contract.md §6.D)
 * @param {string} id
 * @returns {Promise<{alreadyDeleted: boolean}>}
 */
export async function softDeleteFeed(id) {
  const url = `${FEEDS_URL}?id=eq.${encodeURIComponent(id)}&deleted_at=is.null`;
  const response = await rawFetch(url, {
    method: 'PATCH',
    headers: {
      ...BASE_HEADERS,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify({ deleted_at: new Date().toISOString() }),
  });

  if (!response.ok) await throwHttpError(response);
  const rows = await response.json();
  return { alreadyDeleted: rows.length === 0 };
}

/**
 * Corrects a feed's logged time (v1.2). Same idempotent, id-only PATCH shape as
 * `softDeleteFeed` — a feed's id is already globally unique, so this never needs `pet_id`
 * either. `newIso` always comes from `computeEditedTimestamp` (logic.js §7.11), never a raw,
 * unvalidated input value. Never sends `pet_id` or `logged_by`. (contract.md §6.H)
 * @param {string} id
 * @param {string} newIso
 * @returns {Promise<{id: string, pet_id: string, created_at: string, logged_by: string|null, deleted_at: string|null} | {alreadyDeleted: true}>}
 */
export async function updateFeedTime(id, newIso) {
  const url = `${FEEDS_URL}?id=eq.${encodeURIComponent(id)}&deleted_at=is.null`;
  const response = await rawFetch(url, {
    method: 'PATCH',
    headers: {
      ...BASE_HEADERS,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify({ created_at: newIso }),
  });

  if (!response.ok) await throwHttpError(response);
  const rows = await response.json();
  if (rows.length === 0) return { alreadyDeleted: true };
  return rows[0];
}

/**
 * One page of history for `petId`, newest first. (contract.md §6.E)
 * @param {{petId: string, before?: string}} opts - `before` is the created_at of the oldest feed loaded so far
 * @returns {Promise<{feeds: Array, hasMore: boolean}>}
 */
export async function getHistoryPage({ petId, before } = {}) {
  let url =
    `${FEEDS_URL}?select=id,pet_id,created_at,logged_by&pet_id=eq.${encodeURIComponent(petId)}&deleted_at=is.null` +
    `&order=created_at.desc&limit=${HISTORY_PAGE_SIZE}`;
  if (before) {
    url += `&created_at=lt.${encodeURIComponent(before)}`;
  }
  const feeds = await doGet(url);
  return { feeds, hasMore: feeds.length === HISTORY_PAGE_SIZE };
}

/**
 * Pages through every live feed for `petId` (beyond HISTORY_PAGE_SIZE, unlike every other call
 * here) for a full CSV backup export. On any page failing, throws that page's ApiError and
 * discards whatever was already fetched — a partial CSV would be worse than a clear retry.
 * (contract.md §6.F.2)
 * @param {string} petId
 * @returns {Promise<Array>} newest-first, every live feed for this pet
 */
export async function getAllFeedsForExport(petId) {
  const all = [];
  let before;
  for (;;) {
    const { feeds, hasMore } = await getHistoryPage({ petId, before });
    all.push(...feeds);
    if (!hasMore || feeds.length === 0) break;
    before = feeds[feeds.length - 1].created_at;
  }
  return all;
}
