// Pumo Feed Log: the only module that talks to Supabase. Four operations, all REST over fetch.
// Never sends `created_at`. Never uses the HTTP hard-delete verb. (contract.md §6, §8; architecture.md §4)

import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
import { REQUEST_TIMEOUT_MS, RECENT_LIST_SIZE, HISTORY_PAGE_SIZE } from './constants.js';
import { startOfLocalDay } from './logic.js';

const FEEDS_URL = `${SUPABASE_URL}/rest/v1/feeds`;

const BASE_HEADERS = {
  apikey: SUPABASE_PUBLISHABLE_KEY,
  Accept: 'application/json',
};

/**
 * Normalized failure shape for every api.js call. See contract.md §8.
 */
export class ApiError extends Error {
  constructor({ kind, status, code, message }) {
    super(message || kind);
    this.name = 'ApiError';
    this.kind = kind;
    this.status = status;
    this.code = code;
  }
}

/**
 * fetch with cache:'no-store' and a REQUEST_TIMEOUT_MS AbortController, translating every
 * rejection into an ApiError with kind 'timeout' | 'offline' | 'network'.
 */
async function rawFetch(url, options) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    return await fetch(url, { ...options, cache: 'no-store', signal: controller.signal });
  } catch (err) {
    if (controller.signal.aborted) {
      throw new ApiError({ kind: 'timeout', message: 'Request timed out' });
    }
    if (typeof navigator !== 'undefined' && navigator.onLine === false) {
      throw new ApiError({ kind: 'offline', message: 'Offline' });
    }
    throw new ApiError({ kind: 'network', message: (err && err.message) || 'Network error' });
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Throws a normalized 'http' ApiError for a non-OK, non-specially-handled response.
 * Parses and console.errors the PostgREST error body when present.
 * @param {Response} response
 * @returns {Promise<never>}
 */
async function throwHttpError(response) {
  let body = null;
  try {
    body = await response.json();
  } catch {
    // Body wasn't JSON (or was empty) — fall through with body = null.
  }
  if (body) console.error('[Pumo] API error', response.status, body);
  throw new ApiError({
    kind: 'http',
    status: response.status,
    code: body && body.code,
    message: (body && body.message) || response.statusText || `HTTP ${response.status}`,
  });
}

async function doGet(url) {
  const response = await rawFetch(url, { method: 'GET', headers: BASE_HEADERS });
  if (!response.ok) await throwHttpError(response);
  return response.json();
}

/**
 * Last RECENT_LIST_SIZE live feeds, newest first, plus today's live feed count.
 * Both requests run in parallel and both must succeed. (contract.md §6.A/B)
 * @param {Date} now
 * @returns {Promise<{recent: Array, todayCount: number, loadedAt: number}>}
 */
export async function getHomeData(now) {
  const recentUrl =
    `${FEEDS_URL}?select=id,created_at,logged_by&deleted_at=is.null` +
    `&order=created_at.desc&limit=${RECENT_LIST_SIZE}`;

  const since = encodeURIComponent(startOfLocalDay(now).toISOString());
  const countUrl = `${FEEDS_URL}?select=id&deleted_at=is.null&created_at=gte.${since}`;

  const [recent, countRows] = await Promise.all([doGet(recentUrl), doGet(countUrl)]);
  return { recent, todayCount: countRows.length, loadedAt: Date.now() };
}

/**
 * Logs one feed. `id` is generated by the caller (logic.newFeedId) so a retry after a lost
 * response can safely reuse it. Never sends `created_at`. (contract.md §6.C)
 * @param {{id: string, logged_by: string|null}} attempt
 * @returns {Promise<{id: string, created_at: string, logged_by: string|null, deleted_at: string|null}>}
 */
export async function logFeed({ id, logged_by }) {
  const response = await rawFetch(FEEDS_URL, {
    method: 'POST',
    headers: {
      ...BASE_HEADERS,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify({ id, logged_by }),
  });

  if (response.status === 201) {
    const rows = await response.json();
    return rows[0];
  }

  if (response.status === 409) {
    let body = null;
    try {
      body = await response.json();
    } catch {
      // fall through
    }
    if (body && body.code === '23505') {
      // An earlier attempt with this id already reached the database; its response was lost.
      // That's a success, not a failure — fetch the row and resolve with it.
      const rows = await doGet(`${FEEDS_URL}?select=id,created_at,logged_by,deleted_at&id=eq.${encodeURIComponent(id)}`);
      if (rows.length > 0) return rows[0];
    }
    if (body) console.error('[Pumo] API error', response.status, body);
    throw new ApiError({
      kind: 'http',
      status: response.status,
      code: body && body.code,
      message: (body && body.message) || 'Conflict',
    });
  }

  return throwHttpError(response);
}

/**
 * Soft-deletes a feed (used for both Undo and Delete). Only ever PATCHes `deleted_at`. (contract.md §6.D)
 * @param {string} id
 * @returns {Promise<{alreadyDeleted: boolean}>}
 */
export async function softDeleteFeed(id) {
  const url = `${FEEDS_URL}?id=eq.${encodeURIComponent(id)}&deleted_at=is.null`;
  const response = await rawFetch(url, {
    method: 'PATCH',
    headers: {
      ...BASE_HEADERS,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify({ deleted_at: new Date().toISOString() }),
  });

  if (!response.ok) await throwHttpError(response);
  const rows = await response.json();
  return { alreadyDeleted: rows.length === 0 };
}

/**
 * One page of history, newest first. (contract.md §6.E)
 * @param {{before?: string}} [opts] - `before` is the created_at of the oldest feed loaded so far
 * @returns {Promise<{feeds: Array, hasMore: boolean}>}
 */
export async function getHistoryPage({ before } = {}) {
  let url =
    `${FEEDS_URL}?select=id,created_at,logged_by&deleted_at=is.null` +
    `&order=created_at.desc&limit=${HISTORY_PAGE_SIZE}`;
  if (before) {
    url += `&created_at=lt.${encodeURIComponent(before)}`;
  }
  const feeds = await doGet(url);
  return { feeds, hasMore: feeds.length === HISTORY_PAGE_SIZE };
}
